package com.etc.admin.ui.main;

// NodeManager is a simple class uised to track the screen nodes and controllers,
// allowing for simple management and reuse.

import com.etc.admin.ui.account.ViewAccountController;
import com.etc.admin.ui.accountuser.ViewAccountUserController;
import com.etc.admin.ui.associatedproperty.ViewAssociatedPropertyController;
import com.etc.admin.ui.associatedproperty.ViewAssociatedPropertyEditController;
import com.etc.admin.ui.calc.ViewCalcQueueController;
import com.etc.admin.ui.contact.ViewContactController;
import com.etc.admin.ui.department.ViewDepartmentController;
import com.etc.admin.ui.document.ViewDocumentController;
import com.etc.admin.ui.dwi.ViewDWIQueueController;
import com.etc.admin.ui.employee.ViewEmployeeController;
import com.etc.admin.ui.employee.ViewEmployeeMergeController;
import com.etc.admin.ui.employer.ViewEmployerController;
import com.etc.admin.ui.employer.ViewEmployerPayFileController;
import com.etc.admin.ui.employereligibilityperiod.ViewEmployerEligibilityPeriodController;
import com.etc.admin.ui.employmentperiod.ViewEmploymentPeriodController;
import com.etc.admin.ui.export.ViewExportQueueController;
import com.etc.admin.ui.filing.air.ViewAirErrorController;
import com.etc.admin.ui.filing.air.ViewAirFilingEventController;
import com.etc.admin.ui.filing.air.ViewAirStatusRequestController;
import com.etc.admin.ui.filing.air.ViewAirTransmissionController;
import com.etc.admin.ui.home.HomeController;
import com.etc.admin.ui.hr.ViewHRAccountController;
import com.etc.admin.ui.hr.ViewHREmployeeController;
import com.etc.admin.ui.hr.ViewHREmployerController;
import com.etc.admin.ui.localuser.ViewLocalUserController;
import com.etc.admin.ui.payperiod.ViewPayPeriodController;
import com.etc.admin.ui.pipeline.channel.ViewPipelineChannelController;
import com.etc.admin.ui.pipeline.coveragefile.ViewPipelineCoverageFileController;
import com.etc.admin.ui.pipeline.employeefile.ViewPipelineEmployeeFileController;
import com.etc.admin.ui.pipeline.filespecification.ViewDynamicFileSpecificationController;
import com.etc.admin.ui.pipeline.filestephandler.ViewFileStepHandlerController;
import com.etc.admin.ui.pipeline.irs1094cfile.ViewPipelineIRS1094CFileController;
import com.etc.admin.ui.pipeline.irs1095cfile.ViewPipelineIRS1095CFileController;
import com.etc.admin.ui.pipeline.mapper.ViewMapper1095cFormController;
import com.etc.admin.ui.pipeline.mapper.ViewMapperCoverageFormController;
import com.etc.admin.ui.pipeline.mapper.ViewMapperDeductionFormController;
import com.etc.admin.ui.pipeline.mapper.ViewMapperEmployeeFormController;
import com.etc.admin.ui.pipeline.mapper.ViewMapperInsuranceFormController;
import com.etc.admin.ui.pipeline.mapper.ViewMapperPayFileFormController;
import com.etc.admin.ui.pipeline.parsedateformat.ViewParseDateFormatAddController;
import com.etc.admin.ui.pipeline.parsedateformat.ViewParseDateFormatController;
import com.etc.admin.ui.pipeline.parsedateformat.ViewParseDateFormatEditController;
import com.etc.admin.ui.pipeline.parsepattern.ViewParsePatternAddController;
import com.etc.admin.ui.pipeline.parsepattern.ViewParsePatternController;
import com.etc.admin.ui.pipeline.parsepattern.ViewParsePatternEditController;
import com.etc.admin.ui.pipeline.payfile.ViewPipelinePayFileController;
import com.etc.admin.ui.pipeline.queue.ViewPipelineQueueController;
import com.etc.admin.ui.pipeline.queue.ViewPipelineQueueDetailController;
import com.etc.admin.ui.pipeline.raw.ViewPipelineRawFieldGridController;
import com.etc.admin.ui.pipeline.raw.ViewPipelineRawPayController;
import com.etc.admin.ui.pipeline.rowignore.ViewRowIgnoreController;
import com.etc.admin.ui.pipeline.specification.ViewPipelineSpecificationAddController;
import com.etc.admin.ui.pipeline.specification.ViewPipelineSpecificationController;
import com.etc.admin.ui.pipeline.specification.ViewPipelineSpecificationEditController;
import com.etc.admin.ui.plancarrier.ViewPlanCarrierAddController;
import com.etc.admin.ui.plancarrier.ViewPlanCarrierController;
import com.etc.admin.ui.plancarrier.ViewPlanCarrierEditController;
import com.etc.admin.ui.plancoverageclass.ViewPlanCoverageClassAddController;
import com.etc.admin.ui.plancoverageclass.ViewPlanCoverageClassController;
import com.etc.admin.ui.plancoverageclass.ViewPlanCoverageClassEditController;
import com.etc.admin.ui.plansponsor.ViewPlanSponsorAddController;
import com.etc.admin.ui.plansponsor.ViewPlanSponsorController;
import com.etc.admin.ui.plansponsor.ViewPlanSponsorEditController;
import com.etc.admin.ui.planyearoffering.ViewPlanYearOfferingAddController;
import com.etc.admin.ui.planyearoffering.ViewPlanYearOfferingController;
import com.etc.admin.ui.planyearoffering.ViewPlanYearOfferingEditController;
import com.etc.admin.ui.planyearofferingplan.ViewPlanYearOfferingPlanAddController;
import com.etc.admin.ui.planyearofferingplan.ViewPlanYearOfferingPlanController;
import com.etc.admin.ui.planyearofferingplan.ViewPlanYearOfferingPlanEditController;
import com.etc.admin.ui.reports.ViewEtcFilingFailureRptController;
import com.etc.admin.ui.secondary.ViewSecondaryController;
import com.etc.admin.ui.taxmonth.ViewTaxMonthAddController;
import com.etc.admin.ui.taxmonth.ViewTaxMonthController;
import com.etc.admin.ui.taxmonth.ViewTaxMonthEditController;
import com.etc.admin.ui.taxyear.ViewTaxYearAddController;
import com.etc.admin.ui.taxyear.ViewTaxYearController;
import com.etc.admin.ui.taxyear.ViewTaxYearEditController;
import com.etc.admin.ui.uploader.UploadForm;
import com.etc.admin.ui.user.ViewUserAddController;
import com.etc.admin.ui.user.ViewUserController;
import com.etc.admin.ui.user.ViewUserEditController;

import javafx.scene.Parent;

public class NodeManager {

	// controllers
	public HomeController homeController = null;
	public ViewHRAccountController viewHRAccountController= null;
	public ViewHREmployerController viewHREmployerController= null;
	public ViewHREmployeeController viewHREmployeeController= null;
	public ViewEtcFilingFailureRptController viewEtcFilingFailureRptController= null;
	public ViewCalcQueueController viewCalcQueueController = null;
	public ViewDWIQueueController viewDWIQueueController = null;
	public ViewExportQueueController viewExportQueueController = null;
	public ViewPipelineQueueController viewPipelineQueueController = null;
	public ViewPipelineQueueDetailController viewPipelineQueueDetailController = null;
	public ViewPipelineChannelController viewPipelineChannelController = null;
	public ViewPipelineSpecificationController viewPipelineSpecificationController = null;
	public ViewDynamicFileSpecificationController viewDynamicFileSpecificationController = null;
	public ViewMapperCoverageFormController viewMapperCoverageFormController = null;
	public ViewMapperDeductionFormController viewMapperDeductionFormController = null;
	public ViewMapperEmployeeFormController viewMapperEmployeeFormController = null;
	public ViewMapper1095cFormController viewMapper1095cFormController = null;
	public ViewMapperInsuranceFormController viewMapperInsuranceFormController = null;
	public ViewMapperPayFileFormController viewMapperPayFileFormController = null;
//	public ViewDynamicFileSpecificationAddController viewDynamicFileSpecificationAddController = null;
//	public ViewDynamicFileSpecificationEditController viewDynamicFileSpecificationEditController = null;
	public ViewParsePatternController viewParsePatternController = null;
	public ViewParsePatternAddController viewParsePatternAddController = null;
	public ViewParsePatternEditController viewParsePatternEditController = null;
	public ViewParseDateFormatController viewParseDateFormatController = null;
	public ViewParseDateFormatAddController viewParseDateFormatAddController = null;
	public ViewParseDateFormatEditController viewParseDateFormatEditController = null;
	public ViewAccountController viewAccountController= null;
//	public ViewAccountEditController viewAccountEditController = null;
//	public ViewAccountAddController viewAccountAddController = null;
	public ViewAirErrorController viewAirErrorController = null;
//	public ViewAirErrorEditController viewAirErrorEditController = null;
	public ViewAirFilingEventController viewAirFilingEventController = null;
//	public ViewAirFilingEventEditController viewAirFilingEventEditController = null;
	public ViewAirStatusRequestController viewAirStatusRequestController = null;
//	public ViewAirStatusRequestEditController viewAirStatusRequestEditController = null;
	public ViewAirTransmissionController viewAirTransmissionController = null;
//	public ViewAirTransmissionEditController viewAirTransmissionEditController = null;
	public ViewEmployerController viewEmployerController = null;
	public ViewDocumentController viewDocumentController = null;
//	public ViewEmployerEditController viewEmployerEditController = null;
//	public ViewEmployerAddController viewEmployerAddController = null;
	public ViewEmployeeController viewEmployeeController = null;
	public ViewEmployeeMergeController viewEmployeeMergeController = null;
//	public ViewEmployeeEditController viewEmployeeEditController = null;
//	public ViewEmployeeAddController viewEmployeeAddController = null;
	public ViewSecondaryController viewSecondaryController = null;
	public ViewLocalUserController viewLocalUserController = null;
//	public ViewLocalUserEditController viewLocalUserEditController = null;
	public ViewUserController viewUserController = null;
	public ViewUserEditController viewUserEditController = null;
	public ViewUserAddController viewUserAddController = null;
	public ViewAccountUserController viewAccountUserController = null;
//	public ViewAccountUserEditController viewAccountUserEditController = null;
	public ViewPayPeriodController viewPayPeriodController = null;
	public ViewTaxYearController viewTaxYearController = null;
	public ViewTaxYearEditController viewTaxYearEditController = null;
	public ViewTaxYearAddController viewTaxYearAddController = null;
	public ViewTaxMonthController viewTaxMonthController = null;
	public ViewTaxMonthEditController viewTaxMonthEditController = null;
	public ViewTaxMonthAddController viewTaxMonthAddController = null;
	public ViewDepartmentController viewDepartmentController = null;
//	public ViewDepartmentEditController viewDepartmentEditController = null;
//	public ViewDepartmentAddController viewDepartmentAddController = null;
	public ViewEmployerEligibilityPeriodController viewEmployerEligibilityPeriodController = null;
	public ViewEmployerPayFileController viewEmployerPayFileController = null;
	public ViewEmploymentPeriodController viewEmploymentPeriodController = null;
//	public ViewEmploymentPeriodEditController viewEmploymentPeriodEditController = null;
//	public ViewEmploymentPeriodAddController viewEmploymentPeriodAddController = null;
	public ViewAssociatedPropertyController viewAssociatedPropertyController = null;
	public ViewAssociatedPropertyEditController viewAssociatedPropertyEditController = null;
	public ViewContactController viewContactController = null;
//	public ViewContactControllerEdit viewContactEditController = null;
//	public ViewContactControllerAdd viewContactAddController = null;
	public ViewPlanSponsorController viewPlanSponsorController = null;
	public ViewPlanSponsorEditController viewPlanSponsorEditController = null;
	public ViewPlanSponsorAddController viewPlanSponsorAddController = null;
	public ViewPlanCarrierController viewPlanCarrierController = null;
	public ViewPlanCarrierEditController viewPlanCarrierEditController = null;
	public ViewPlanCarrierAddController viewPlanCarrierAddController = null;
	public ViewPlanYearOfferingController viewPlanYearOfferingController = null;
	public ViewPlanYearOfferingEditController viewPlanYearOfferingEditController = null;
	public ViewPlanYearOfferingAddController viewPlanYearOfferingAddController = null;
	public ViewPlanYearOfferingPlanController viewPlanYearOfferingPlanController = null;
	public ViewPlanYearOfferingPlanEditController viewPlanYearOfferingPlanEditController = null;
	public ViewPlanYearOfferingPlanAddController viewPlanYearOfferingPlanAddController = null;
	public ViewPlanCoverageClassController viewPlanCoverageClassController = null;
	public ViewPlanCoverageClassEditController viewPlanCoverageClassEditController = null;
	public ViewPlanCoverageClassAddController viewPlanCoverageClassAddController = null;
//	public ViewPipelineChannelEditController viewPipelineChannelEditController = null;
//	public ViewPipelineChannelAddController viewPipelineChannelAddController = null;
	public ViewPipelineSpecificationEditController viewPipelineSpecificationEditController = null;
	public ViewPipelineSpecificationAddController viewPipelineSpecificationAddController = null;
	public ViewPipelinePayFileController viewPipelinePayFileController = null;
//	public ViewPipelinePayFileAddController viewPipelinePayFileAddController = null;
//	public ViewPipelinePayFileEditController viewPipelinePayFileEditController = null;
	public ViewPipelineEmployeeFileController viewPipelineEmployeeFileController = null;
//	public ViewPipelineEmployeeFileEditController viewPipelineEmployeeFileEditController = null;
//	public ViewPipelineEmployeeFileAddController viewPipelineEmployeeFileAddController = null;
	public ViewPipelineCoverageFileController viewPipelineCoverageFileController = null;
//	public ViewPipelineCoverageFileEditController viewPipelineCoverageFileEditController = null;
//	public ViewPipelineCoverageFileAddController viewPipelineCoverageFileAddController = null;
	public ViewPipelineIRS1094CFileController viewPipelineIRS1094CFileController = null;
	public ViewPipelineIRS1095CFileController viewPipelineIRS1095CFileController = null;
	public ViewPipelineRawFieldGridController viewPipelineRawFieldGridController = null;
	public ViewPipelineRawPayController viewPipelineRawPayController = null;
	public ViewRowIgnoreController viewRowIgnoreController = null;
	public ViewFileStepHandlerController viewFileStepHandlerController = null;
//	public ViewFileStepHandlerEditController viewFileStepHandlerEditController = null;
//	public ViewFileStepHandlerAddController viewFileStepHandlerAddController = null;
//	public ViewPipelineIRS1094CFileEditController viewPipelineIRS1094CFileEditController = null;
//	public ViewPipelineIRS1095CFileEditController viewPipelineIRS1095CFileEditController = null;
	public UploadForm uploadForm = null;
	
	// nodes
	public Parent homeControllerNode = null;
	public Parent viewHRAccountControllerNode = null;
	public Parent viewHREmployerControllerNode = null;
	public Parent viewHREmployeeControllerNode = null;
	public Parent viewEtcFilingFailureRptControllerNode = null;
	public Parent viewRowIgnoreControllerNode = null;
	public Parent viewCalcQueueControllerNode = null;
	public Parent viewDWIQueueControllerNode = null;
	public Parent viewDocumentControllerNode = null;
	public Parent viewExportQueueControllerNode = null;
	public Parent viewPipelineQueueControllerNode = null;
	public Parent viewPipelineQueueDetailControllerNode = null;
	public Parent viewPipelineChannelControllerNode = null;
	public Parent viewPipelineSpecificationControllerNode = null;
	public Parent viewDynamicFileSpecificationControllerNode = null;
	public Parent viewMapperCoverageFormControllerNode = null;
	public Parent viewMapperDeductionFormControllerNode = null;
	public Parent viewMapperEmployeeFormControllerNode = null;
	public Parent viewMapperInsuranceFormControllerNode = null;
	public Parent viewMapper1095cFormControllerNode = null;
	public Parent viewMapperPayFileFormControllerNode = null;
	public Parent viewDynamicFileSpecificationAddControllerNode = null;
	public Parent viewDynamicFileSpecificationEditControllerNode = null;
	public Parent viewParsePatternControllerNode = null;
	public Parent viewParsePatternAddControllerNode = null;
	public Parent viewParsePatternEditControllerNode = null;
	public Parent viewParseDateFormatControllerNode = null;
	public Parent viewParseDateFormatEditControllerNode = null;
	public Parent viewParseDateFormatAddControllerNode = null;
	public Parent viewAccountControllerNode = null;
	public Parent viewAccountEditControllerNode = null;
	public Parent viewAccountAddControllerNode = null;
	public Parent viewAirErrorControllerNode = null;
	public Parent viewAirErrorEditControllerNode = null;
	public Parent viewAirFilingEventControllerNode = null;
	public Parent viewAirFilingEventEditControllerNode = null;
	public Parent viewAirStatusRequestControllerNode = null;
	public Parent viewAirStatusRequestEditControllerNode = null;
	public Parent viewAirTransmissionControllerNode = null;
	public Parent viewAirTransmissionEditControllerNode = null;
	public Parent viewEmployeeMergeControllerNode = null;
	public Parent viewEmployerControllerNode = null;
	public Parent viewEmployerEditControllerNode = null;
	public Parent viewEmployerAddControllerNode = null;
	public Parent viewEmployeeControllerNode = null;
	public Parent viewEmployeeEditControllerNode = null;
	public Parent viewEmployeeAddControllerNode = null;
	public Parent viewSecondaryControllerNode = null;
	public Parent viewSecondaryEditControllerNode = null;
	public Parent viewSecondaryAddControllerNode = null;
	public Parent viewLocalUserControllerNode = null;
	public Parent viewLocalUserEditControllerNode = null;
	public Parent viewUserControllerNode = null;
	public Parent viewUserEditControllerNode = null;
	public Parent viewUserAddControllerNode = null;
	public Parent viewAccountUserControllerNode = null;
	public Parent viewAccountUserEditControllerNode = null;
	public Parent viewPayPeriodControllerNode = null;
	public Parent viewTaxYearControllerNode = null;
	public Parent viewTaxYearEditControllerNode = null;
	public Parent viewTaxYearAddControllerNode = null;
	public Parent viewTaxMonthControllerNode = null;
	public Parent viewTaxMonthEditControllerNode = null;
	public Parent viewTaxMonthAddControllerNode = null;
	public Parent viewDepartmentControllerNode = null;
	public Parent viewDepartmentEditControllerNode = null;
	public Parent viewDepartmentAddControllerNode = null;
	public Parent viewEmployeeCoveragePeriodControllerNode = null;
	public Parent viewEmployeeCoveragePeriodEditControllerNode = null;
	public Parent viewEmployeeCoveragePeriodAddControllerNode = null;
	public Parent viewEmployerEligibilityPeriodControllerNode = null;
	public Parent viewEmployerPayFileControllerNode = null;
	public Parent viewEmploymentPeriodControllerNode = null;
	public Parent viewEmploymentPeriodEditControllerNode = null;
	public Parent viewEmploymentPeriodAddControllerNode = null;
	public Parent viewAssociatedPropertyControllerNode = null;
	public Parent viewAssociatedPropertyEditControllerNode = null;
	public Parent viewContactControllerNode = null;
	public Parent viewContactEditControllerNode = null;
	public Parent viewContactAddControllerNode = null;
	public Parent viewPlanControllerNode = null;
	public Parent viewPlanEditControllerNode = null;
	public Parent viewPlanAddControllerNode = null;
	public Parent viewPlanProviderControllerNode = null;
	public Parent viewPlanProviderEditControllerNode = null;
	public Parent viewPlanProviderAddControllerNode = null;
	public Parent viewPlanSponsorControllerNode = null;
	public Parent viewPlanSponsorEditControllerNode = null;
	public Parent viewPlanSponsorAddControllerNode = null;
	public Parent viewPlanCarrierControllerNode = null;
	public Parent viewPlanCarrierEditControllerNode = null;
	public Parent viewPlanCarrierAddControllerNode = null;
	public Parent viewPlanYearOfferingControllerNode = null;
	public Parent viewPlanYearOfferingEditControllerNode = null;
	public Parent viewPlanYearOfferingAddControllerNode = null;
	public Parent viewPlanYearOfferingPlanControllerNode = null;
	public Parent viewPlanYearOfferingPlanEditControllerNode = null;
	public Parent viewPlanYearOfferingPlanAddControllerNode = null;
	public Parent viewPlanCoverageClassControllerNode = null;
	public Parent viewPlanCoverageClassEditControllerNode = null;
	public Parent viewPlanCoverageClassAddControllerNode = null;
	public Parent viewPipelineChannelEditControllerNode = null;
	public Parent viewPipelineChannelAddControllerNode = null;
	public Parent viewPipelineSpecificationEditControllerNode = null;
	public Parent viewPipelineSpecificationAddControllerNode = null;
	public Parent viewPipelinePayFileControllerNode = null;
	public Parent viewPipelinePayFileAddControllerNode = null;
	public Parent viewPipelinePayFileEditControllerNode = null;
	public Parent viewPipelineEmployeeFileControllerNode = null;
	public Parent viewPipelineEmployeeFileEditControllerNode = null;
	public Parent viewPipelineEmployeeFileAddControllerNode = null;
	public Parent viewPipelineCoverageFileControllerNode = null;
	public Parent viewPipelineCoverageFileEditControllerNode = null;
	public Parent viewPipelineCoverageFileAddControllerNode = null;
	public Parent viewPipelineIRS1094CFileControllerNode = null;
	public Parent viewPipelineIRS1095CFileControllerNode = null;
	public Parent viewPipelineRawFieldGridControllerNode = null;
	public Parent viewPipelineRawPayControllerNode = null;
	public Parent viewFileStepHandlerControllerNode = null;
	public Parent viewFileStepHandlerEditControllerNode = null;
	public Parent viewFileStepHandlerAddControllerNode = null;
	public Parent viewPipelineIRS1094CFileEditControllerNode = null;
	public Parent viewPipelineIRS1095CFileEditControllerNode = null;
	public Parent uploadFormNode = null;

}
